<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class StateSeeder extends Seeder
{
    public function run(): void
    {
        /*
         * Data sources:
         *  - Coordinates: GeoNames / OpenStreetMap state centroids
         *  - Postal prefixes: NIPOST zone codes
         *  - ISO codes: ISO 3166-2:NG
         *  - Geo zones: Nigerian Federal Government classification
         */
        $states = [
            [
                'name' => 'Abia',
                'slug' => 'abia',
                'capital' => 'Umuahia',
                'geo_zone' => 'SE',
                'geo_zone_full' => 'South East',
                'lat' => 5.4527,
                'lng' => 7.5248,
                'postal_prefix' => '450',
                'iso_code' => 'NG-AB',
            ],
            [
                'name' => 'Adamawa',
                'slug' => 'adamawa',
                'capital' => 'Yola',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 9.3265,
                'lng' => 12.3984,
                'postal_prefix' => '640',
                'iso_code' => 'NG-AD',
            ],
            [
                'name' => 'Akwa Ibom',
                'slug' => 'akwa-ibom',
                'capital' => 'Uyo',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 4.9057,
                'lng' => 7.8536,
                'postal_prefix' => '520',
                'iso_code' => 'NG-AK',
            ],
            [
                'name' => 'Anambra',
                'slug' => 'anambra',
                'capital' => 'Awka',
                'geo_zone' => 'SE',
                'geo_zone_full' => 'South East',
                'lat' => 6.2107,
                'lng' => 7.0673,
                'postal_prefix' => '420',
                'iso_code' => 'NG-AN',
            ],
            [
                'name' => 'Bauchi',
                'slug' => 'bauchi',
                'capital' => 'Bauchi',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 10.3158,
                'lng' => 9.8442,
                'postal_prefix' => '740',
                'iso_code' => 'NG-BA',
            ],
            [
                'name' => 'Bayelsa',
                'slug' => 'bayelsa',
                'capital' => 'Yenagoa',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 4.7719,
                'lng' => 6.0699,
                'postal_prefix' => '561',
                'iso_code' => 'NG-BY',
            ],
            [
                'name' => 'Benue',
                'slug' => 'benue',
                'capital' => 'Makurdi',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 7.1906,
                'lng' => 8.1302,
                'postal_prefix' => '970',
                'iso_code' => 'NG-BE',
            ],
            [
                'name' => 'Borno',
                'slug' => 'borno',
                'capital' => 'Maiduguri',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 11.8469,
                'lng' => 13.1572,
                'postal_prefix' => '600',
                'iso_code' => 'NG-BO',
            ],
            [
                'name' => 'Cross River',
                'slug' => 'cross-river',
                'capital' => 'Calabar',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 5.9631,
                'lng' => 8.3302,
                'postal_prefix' => '540',
                'iso_code' => 'NG-CR',
            ],
            [
                'name' => 'Delta',
                'slug' => 'delta',
                'capital' => 'Asaba',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 5.7041,
                'lng' => 5.9328,
                'postal_prefix' => '330',
                'iso_code' => 'NG-DE',
            ],
            [
                'name' => 'Ebonyi',
                'slug' => 'ebonyi',
                'capital' => 'Abakaliki',
                'geo_zone' => 'SE',
                'geo_zone_full' => 'South East',
                'lat' => 6.2649,
                'lng' => 8.0137,
                'postal_prefix' => '840',
                'iso_code' => 'NG-EB',
            ],
            [
                'name' => 'Edo',
                'slug' => 'edo',
                'capital' => 'Benin City',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 6.3350,
                'lng' => 5.6037,
                'postal_prefix' => '300',
                'iso_code' => 'NG-ED',
            ],
            [
                'name' => 'Ekiti',
                'slug' => 'ekiti',
                'capital' => 'Ado Ekiti',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 7.7190,
                'lng' => 5.3110,
                'postal_prefix' => '360',
                'iso_code' => 'NG-EK',
            ],
            [
                'name' => 'Enugu',
                'slug' => 'enugu',
                'capital' => 'Enugu',
                'geo_zone' => 'SE',
                'geo_zone_full' => 'South East',
                'lat' => 6.4584,
                'lng' => 7.5464,
                'postal_prefix' => '400',
                'iso_code' => 'NG-EN',
            ],
            [
                'name' => 'FCT',
                'slug' => 'fct',
                'capital' => 'Abuja',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 9.0765,
                'lng' => 7.3986,
                'postal_prefix' => '900',
                'iso_code' => 'NG-FC',
            ],
            [
                'name' => 'Gombe',
                'slug' => 'gombe',
                'capital' => 'Gombe',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 10.2791,
                'lng' => 11.1671,
                'postal_prefix' => '760',
                'iso_code' => 'NG-GO',
            ],
            [
                'name' => 'Imo',
                'slug' => 'imo',
                'capital' => 'Owerri',
                'geo_zone' => 'SE',
                'geo_zone_full' => 'South East',
                'lat' => 5.5720,
                'lng' => 7.0588,
                'postal_prefix' => '460',
                'iso_code' => 'NG-IM',
            ],
            [
                'name' => 'Jigawa',
                'slug' => 'jigawa',
                'capital' => 'Dutse',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 12.2280,
                'lng' => 9.5616,
                'postal_prefix' => '720',
                'iso_code' => 'NG-JI',
            ],
            [
                'name' => 'Kaduna',
                'slug' => 'kaduna',
                'capital' => 'Kaduna',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 10.5167,
                'lng' => 7.4333,
                'postal_prefix' => '800',
                'iso_code' => 'NG-KD',
            ],
            [
                'name' => 'Kano',
                'slug' => 'kano',
                'capital' => 'Kano',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 12.0022,
                'lng' => 8.5920,
                'postal_prefix' => '700',
                'iso_code' => 'NG-KN',
            ],
            [
                'name' => 'Katsina',
                'slug' => 'katsina',
                'capital' => 'Katsina',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 12.9889,
                'lng' => 7.6006,
                'postal_prefix' => '820',
                'iso_code' => 'NG-KT',
            ],
            [
                'name' => 'Kebbi',
                'slug' => 'kebbi',
                'capital' => 'Birnin Kebbi',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 11.4942,
                'lng' => 4.2333,
                'postal_prefix' => '860',
                'iso_code' => 'NG-KE',
            ],
            [
                'name' => 'Kogi',
                'slug' => 'kogi',
                'capital' => 'Lokoja',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 7.7337,
                'lng' => 6.6906,
                'postal_prefix' => '260',
                'iso_code' => 'NG-KO',
            ],
            [
                'name' => 'Kwara',
                'slug' => 'kwara',
                'capital' => 'Ilorin',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 8.9669,
                'lng' => 4.5877,
                'postal_prefix' => '240',
                'iso_code' => 'NG-KW',
            ],
            [
                'name' => 'Lagos',
                'slug' => 'lagos',
                'capital' => 'Ikeja',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 6.5244,
                'lng' => 3.3792,
                'postal_prefix' => '100',
                'iso_code' => 'NG-LA',
            ],
            [
                'name' => 'Nasarawa',
                'slug' => 'nasarawa',
                'capital' => 'Lafia',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 8.4966,
                'lng' => 8.5257,
                'postal_prefix' => '950',
                'iso_code' => 'NG-NA',
            ],
            [
                'name' => 'Niger',
                'slug' => 'niger',
                'capital' => 'Minna',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 9.9309,
                'lng' => 5.5983,
                'postal_prefix' => '920',
                'iso_code' => 'NG-NI',
            ],
            [
                'name' => 'Ogun',
                'slug' => 'ogun',
                'capital' => 'Abeokuta',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 7.1475,
                'lng' => 3.3619,
                'postal_prefix' => '110',
                'iso_code' => 'NG-OG',
            ],
            [
                'name' => 'Ondo',
                'slug' => 'ondo',
                'capital' => 'Akure',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 7.2526,
                'lng' => 5.1986,
                'postal_prefix' => '340',
                'iso_code' => 'NG-ON',
            ],
            [
                'name' => 'Osun',
                'slug' => 'osun',
                'capital' => 'Osogbo',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 7.5629,
                'lng' => 4.5200,
                'postal_prefix' => '230',
                'iso_code' => 'NG-OS',
            ],
            [
                'name' => 'Oyo',
                'slug' => 'oyo',
                'capital' => 'Ibadan',
                'geo_zone' => 'SW',
                'geo_zone_full' => 'South West',
                'lat' => 7.8504,
                'lng' => 3.9470,
                'postal_prefix' => '200',
                'iso_code' => 'NG-OY',
            ],
            [
                'name' => 'Plateau',
                'slug' => 'plateau',
                'capital' => 'Jos',
                'geo_zone' => 'NC',
                'geo_zone_full' => 'North Central',
                'lat' => 9.2182,
                'lng' => 9.5179,
                'postal_prefix' => '930',
                'iso_code' => 'NG-PL',
            ],
            [
                'name' => 'Rivers',
                'slug' => 'rivers',
                'capital' => 'Port Harcourt',
                'geo_zone' => 'SS',
                'geo_zone_full' => 'South South',
                'lat' => 4.8156,
                'lng' => 7.0498,
                'postal_prefix' => '500',
                'iso_code' => 'NG-RI',
            ],
            [
                'name' => 'Sokoto',
                'slug' => 'sokoto',
                'capital' => 'Sokoto',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 13.0059,
                'lng' => 5.2476,
                'postal_prefix' => '840',
                'iso_code' => 'NG-SO',
            ],
            [
                'name' => 'Taraba',
                'slug' => 'taraba',
                'capital' => 'Jalingo',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 7.8704,
                'lng' => 11.3667,
                'postal_prefix' => '660',
                'iso_code' => 'NG-TA',
            ],
            [
                'name' => 'Yobe',
                'slug' => 'yobe',
                'capital' => 'Damaturu',
                'geo_zone' => 'NE',
                'geo_zone_full' => 'North East',
                'lat' => 12.2938,
                'lng' => 11.4390,
                'postal_prefix' => '620',
                'iso_code' => 'NG-YO',
            ],
            [
                'name' => 'Zamfara',
                'slug' => 'zamfara',
                'capital' => 'Gusau',
                'geo_zone' => 'NW',
                'geo_zone_full' => 'North West',
                'lat' => 12.1704,
                'lng' => 6.6574,
                'postal_prefix' => '860',
                'iso_code' => 'NG-ZA',
            ],
        ];

        foreach ($states as $state) {
            State::updateOrCreate(
                ['name' => $state['name']],
                array_merge($state, ['country_code' => 'NG'])
            );
        }

        $this->command->info('StateSeeder: ' . count($states) . ' states seeded.');
    }
}
